### ISSUE TITLE
some bitnami charts fail to render the readme or metadata

### ISSUE THREAD

**Issue by vrabbi** [bitnami-labs/readme-generator-for-helm#21] opened 2021-10-12 16:25 UTC
the following bitnami charts fail to render via this project due to multiple issues:
"KEY_OVER_1024_CHARS":
1.  mongodb
2. grafana-operator

"Wrong Metadata":
1. mariadb-cluster
2. mean
3. prometheus-operator
4. sugarcrm
5. tensorflow-inception

the wrong metadata seems to be because these charts do not have any metadata in them used by this project which i think is an issue as it should be standard in all bitnami charts.
the key over 1024 chars issue seems to be an underlying YAML parser issue but should be considered how to fix in this project or in the chart as its a bad UX when not all charts render as expected

**Comment by miguelaeh** [comment] 2021-10-20 08:11
Hi @vrabbi ,]
We marc them as DEPRECATED in the index, for example:
```
bitnami/mean                                	6.1.2        	4.6.2        	DEPRECATED MEAN is a free and open-source JavaS...
```
but we don't remove them.
Isn't it possible for you to search the charts on the GH repo?

**Comment by MikaelElkiaer** [comment] 2021-11-24 13:55
> so the mongodb issue was a bad node installation i had which the commander module was broken in. regardin the other charts, the issue is that they are still in the chart repo. they have been removed from github but if you add the repo and run a search they are still there. i have been doing some automation around generating carvel packages from the bitnami charts and was doing the helm search programitcally against the repo. is there a way in helm search to not show the bitnami deprecated charts? are the bitnami team planning on removing those charts completely?

I am facing the same issue right now. What exactly did you do to fix your node installation?

**Comment by miguelaeh** [comment] 2021-11-25 09:47
Hi @MikaelElkiaer ,
You can delete the `node_modules` directory and execute `npm install` again from inside the directory where you cloned the tool.

**Comment by MikaelElkiaer** [comment] 2021-11-25 11:05
> Hi @MikaelElkiaer , You can delete the `node_modules` directory and execute `npm install` again from inside the directory where you cloned the tool.

Thanks for the reply.

I ended up uninstalling the globally installed version and cloning and running instead.

**Comment by miguelaeh** [comment] 2021-11-26 08:54
Since the issue is solved I will close the issue

**Closed by miguelaeh** 2021-11-26 08:54 UTC
