### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by politician** [bitnami-labs/readme-generator-for-helm#36] opened 2022-03-21 07:06 UTC
This should be published on npm for easier consumption

**Comment by miguelaeh** [comment] 2022-03-21 10:14
Hi, 
There is already someone publishing it https://www.npmjs.com/package/readme-generator-for-helm

**Comment by politician** [comment] 2022-03-21 11:43
Hi @miguelaeh Can I open a PR to add it to the README?

It would save some hassle when contributing to the bitnami charts repo.

**Comment by miguelaeh** [comment] 2022-03-22 09:18
Sure!

**Comment by politician** [comment] 2022-03-22 11:02
Ok I just did some due diligence before adding it: the [author's fork](https://github.com/alexjamesmalcolm/readme-generator-for-helm) is not automatically updated and differs slightly from the official repo.

Current options I see:

1. @miguelaeh would it be possible to add a @bitnami NPM token in the GitHub actions secrets? I'm happy to draft an auto-publish action so this repo can publish to https://www.npmjs.com/package/@bitnami/readme-generator-for-helm
2. @alexjamesmalcolm would you consider replacing the https://www.npmjs.com/package/readme-generator-for-helm with code from this repo and auto-publish on a schedule? You can achieve this with GH actions as well and I'm happy to help
3. @alexjamesmalcolm if you don't want to be bothered, would you consider transferring the package to [me](https://www.npmjs.com/~iromain)?

**Comment by alexjamesmalcolm** [comment] 2022-03-23 14:48
Hello, sorry for accidentally publishing this, I made a mistake when I was trying to publish it as `@alexjamesmalcolm/readme-generator-for-helm`. @miguelaeh, do you have any thoughts on me transferring the NPM package to @politician?

**Comment by justusbunsi** [comment] 2022-06-07 18:22
Hi. Following this issue for a while now. Would there be any disadvantage of publishing it within the `@bitnami` namespace? It seems to be some sort of a deadlock situation right now; speaking from an external point of view.

**Comment by agomezmoron** [comment] 2022-10-10 14:39
Hi @alexjamesmalcolm, we need you to transfer that npm package to Bitnami (https://www.npmjs.com/org/bitnami) because we are the maintainers. Please, could you let me know when you addressed it in order to work on our side to publish updates there?

Cheers

**Comment by justusbunsi** [comment] 2022-10-13 11:25
Would it be a solution to rename the package in `package.json` to `<at>bitnami/readme-generator-for-helm` and publish it as such? That way the transfer wouldn't be necessary for this issue to be resolved.
Or do you want to publish it outside the org scope on NPM?

Drawback: Different package name. Package usages referring to GitHub might be broken?

**Comment by agomezmoron** [comment] 2022-10-13 17:00
Hi @justusbunsi, that's not the solution. The problem is @alexjamesmalcolm published our package under his scope and it shouldn't be in that way according to the product. That's why the easiest and cleanest solution IMHO is transferring the package to the org which it belongs to.

Thank you for the heads up!

**Comment by justusbunsi** [comment] 2022-10-13 17:03
Fair point. Sounds reasonable. 👍

**Comment by alexjamesmalcolm** [comment] 2022-10-13 19:09
Hello @agomezmoron.

I'm following this [NPM documentation](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-another-user-account) and trying to add "bitnami" as a maintainer and then remove myself, thus transferring ownership. The problem is that "bitnami" is an organization and you cannot invite organizations.

I was able to find @miguelaeh on NPM as [angelrb](https://www.npmjs.com/~angelrb) so I have invited @miguelaeh to be a maintainer. Once @miguelaeh accepts the invitation I'll remove myself and then hopefully it can be managed under @bitnami somehow.

**Comment by agomezmoron** [comment] 2022-10-14 12:11
Hi @alexjamesmalcolm,

Thank you. @miguelaeh is not part of Bitnami currently so I think the easiest easiest way can be:
* You unpublish it https://docs.npmjs.com/unpublishing-packages-from-the-registry
* Once unpublished, we will publish it as owners.

Thanks

**Comment by alexjamesmalcolm** [comment] 2022-10-18 03:28
@agomezmoron I unpublished/deleted the package.

**Comment by agomezmoron** [comment] 2022-10-18 04:34
Thank you @alexjamesmalcolm , we will work in its publication then.

**Comment by harjotgill** [comment] 2022-10-18 04:46
Waiting anxiously for this to get published as our CI is now broken! :)

**Comment by agomezmoron** [comment] 2022-10-19 13:55
The package was published on [npm](https://www.npmjs.com/package/@bitnami/readme-generator-for-helm) and will keep publishing with the incoming changes.

I'll close this issue then.

Cheers

**Closed by agomezmoron** 2022-10-19 13:55 UTC

**Comment by brsolomon-deloitte** [comment] 2022-12-14 15:53
It looks like `@bitnami/readme-generator-for-helm` is available on NPM, but the readme here still suggests installing from Git.
